<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <link rel="stylesheet" href="/account_b2c/resources/css/app.css">
  <title>${title}</title>
</head>
<body>
  <div class="cud-wrapper">
    <div id="kc-logo"></div>
    <div class="cud-content">
      <div class="cud-content-header">
        <h1 class="h">Контактные данные</h1>
      </div>
      <div class="cud-content-desc" style="height: 296px;">
        <p class="description">Ваш email был подтвержден</p>
      </div>
      <a class="btn primary-orange" id="t-href-ok" href="${base_uri}" style="position: absolute; bottom: 20px; text-decoration: none;">Продолжить</a>
    </div>
  </div>
</body>
</html>